version: "3.9"
services:
    app:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
        platform: linux/arm64
        restart: always
        ports:
            - "80"
        container_name: ${APP_NAME}_app
        environment:
            VIRTUAL_HOST: ${HOST_DOMAIN}
            LETSENCRYPT_HOST: ${HOST_DOMAIN}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        volumes:
            - app-mydb:/app/App_Data
    app-migration:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
        platform: linux/arm64
        restart: "no"
        container_name: ${APP_NAME}_app_migration
        profiles:
            - migration
        command: --AppTasks=migrate
        volumes:
            - app-mydb:/app/App_Data
    benchmark-client:
      build:
        dockerfile: ./BenchmarkClient/Dockerfile
        context: .
      platform: linux/arm64
      depends_on:
        - app
      profiles:
        - test
      command: ["http://app:80"]
      networks:
        - mynet

networks:
  default:
    external: true
    name: nginx

volumes:
    app-mydb: