version: "3.9"
services:
    app:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
        platform: linux/arm64
        restart: always
        ports:
            - "80"
        container_name: ${APP_NAME}_app
        environment:
            VIRTUAL_HOST: ${HOST_DOMAIN}
            LETSENCRYPT_HOST: ${HOST_DOMAIN}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        volumes:
            - app-mydb:/app/App_Data
    app-migration:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
        platform: linux/arm64
        restart: "no"
        container_name: ${APP_NAME}_app_migration
        profiles:
            - migration
        command: --AppTasks=migrate
        volumes:
            - app-mydb:/app/App_Data
    gatling:
        build: ./gatling
        platform: linux/arm64
        volumes:
          - ./gatling/conf:/opt/gatling/conf
          - ./gatling/results:/opt/gatling/target/gatling
          - ./gatling/src:/opt/gatling/src
        depends_on:
          - app
        profiles:
          - test
        command: mvn gatling:test

networks:
  default:
    external: true
    name: nginx

volumes:
    app-mydb: