version: "3.9"
services:
  app:
    build: .
    container_name: app
    ports:
      - "5000:80"
    volumes:
      - app-mydb:/app/App_Data
    networks:
      - mynet
  app-migration:
    build: .
    restart: "no"
    profiles:
      - migration
    command: --AppTasks=migrate
    volumes:
      - app-mydb:/app/App_Data
  benchmark-client:
    build:
      dockerfile: ./BenchmarkClient/Dockerfile
      context: .
    depends_on:
      - app
    profiles:
      - test
    command: ["http://app:80"]
    networks:
      - mynet

volumes:
  app-mydb:

networks:
  mynet: